apiVersion: v1
kind: Service
metadata:
  name: companiesnpservice-srv
spec:
  type: NodePort
  selector:
    app: companiesservice
  ports:
    - name: companiesservice
      protocol: TCP
      port: 80
      targetPort: 80